version: '2'

services:
  pmm-data:
    build: .
    image: percona/pmm-server
    container_name: pmm-data
    volumes:
      - /opt/prometheus/data
      - /opt/consul-data
      - /var/lib/mysql
      - /var/lib/grafana
    entrypoint: /bin/true

  pmm-server:
    build: .
    container_name: pmm-server
    image: percona/pmm-server
    restart: always
    ports:
      - "80:80"
#      - "443:443"
    volumes_from:
      - pmm-data
#    volumes:
#      - /root/docker_shared_volumes/ssl:/srv/nginx
    environment:
      - METRICS_RETENTION=720h
      - METRICS_MEMORY=262144
      - METRICS_RESOLUTION=1s
      - QUERIES_RETENTION=8
      - ORCHESTRATOR_USER=orc_client_user
      - ORCHESTRATOR_PASSWORD=orc_client_password
      - SERVER_USER=pmm
      - SERVER_PASSWORD=
      - PROMETHEUS_EVALUATION_INTERVAL=60s
      - PROMETHEUS_RULE_FILES=
